### ISSUE TITLE
Email confirmation is failing in Dev Environment

### ISSUE THREAD

**Issue by Gustavo-SF** [LDSSA/portal#318]
## Problem

Can't confirm email after creating an account in the development environment.

**Comment by brunodaemon2** [comment]
Error found running reset password locally:
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/accounts/password/reset/

Django Version: 4.2.14
Python Version: 3.10.15
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'constance',
 'constance.backends.database',
 'crispy_forms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'rest_framework.authtoken',
 'crispy_bootstrap4',
 'portal.users.apps.UsersAppConfig',
 'portal.academy.apps.AcademyConfig',
 'portal.hackathons.apps.HackathonsConfig',
 'portal.capstone.apps.CapstoneConfig',
 'portal.admissions.apps.AdmissionsConfig',
 'portal.applications.apps.ApplicationsConfig',
 'portal.candidate.apps.CandidateConfig',
 'portal.staff.apps.StaffConfig',
 'portal.selection.apps.SelectionConfig',
 'portal.grading.apps.GradingConfig',
 'portal.scheduler.apps.SchedulerConfig',
 'compressor',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'allauth.account.middleware.AccountMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback (most recent call last):
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/allauth/account/mixins.py", line 82, in post
    response = self.form_valid(form)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/allauth/account/views.py", line 582, in form_valid
    form.save(self.request)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/allauth/account/forms.py", line 633, in save
    adapter.send_password_reset_mail(user, email, context)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/allauth/account/adapter.py", line 577, in send_password_reset_mail
    return self.send_mail("account/email/password_reset_key", email, context)
  File "/Users/brunodaemon/PycharmProjects/ldsa/portal/portal/portal/portal/users/adapters.py", line 85, in send_mail
    send_reset_password_email(to_email=email, reset_password_url=url)
  File "/Users/brunodaemon/PycharmProjects/ldsa/portal/portal/portal/portal/admissions/emails.py", line 24, in send_reset_password_email
    email.send()
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/core/mail/message.py", line 299, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/socket.py", line 836, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/anaconda3/envs/ldsa/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

Exception Type: gaierror at /accounts/password/reset/
Exception Value: [Errno 8] nodename nor servname provided, or not known

**Comment by brunodaemon2** [comment]
1. I found out that the same workflow is working in [dev Portal ](https://portal.dev-lisbondatascience.org/accounts/password/reset/done/)
2. Researching the error I found out that this might be a permission error to access the SMTP server from the IP address from my local machine.
![Image](https://github.com/user-attachments/assets/623163ea-c577-4ec0-9771-4fab77a17df0)
